[replit]
version = "1"
modules = ["python-3.11"]

[nix]
channel = "stable-23_11"

[deployment]
run = ["python", "-m", "flask", "--app", "main", "run", "--host=0.0.0.0", "--port=5000"]
deploymentTarget = "webservice"

[ports]
localPort = 5000
externalPort = 80